#  inputs.py
#  Inputs to be provided by the user before running
#  Four inputs to be provided
#
#  Updated by Xavier Vasques on 19/02/2015.

import os
import configuration

#########################################################################
#                                                                       #
# Please provide the necessary inputs before running data analysis      #
#                                                                       #
#########################################################################

#########################################################################
# Provide the main folder location where the morphologies can be found.
# Under the main folder, you can have sub-folders and then the
# morphology files. Example: Morphologies (main folder) -> Class_1,
# Class_2, Class_3 ... (sub-folders) -> neuron_1.swc, neuron_2.swc,
# neuron_3.swc .... (morphology files)

main_directory="/Users/Xavi/Desktop/Classification/"

morphology=main_directory+"Morphologies/"
#########################################################################


#########################################################################
# After downloading L-Measure, we need to run the lmeasure command line.
# Provide the location of the L-Measure binary
# Example:'./Lmv5.2/lmeasure'
# Orginal files generated by L-Measure will be stored in the main folder
# location
l_measure_command='./Lmv5.2/lmeasure'
##########################################################################

# Extracted features by class output folder: Give a location where to
# save the extracted features by class (sub-folders) using L-Measure
# The folder will be automatically created
features_output=main_directory+"Extracted_Features/"
##########################################################################


##########################################################################
# Data Anlysis Output folder: Give a location to put results from Data Analysis
# The folder will be automatically created
data_analysis=main_directory+"Data_Analysis_"+configuration.result_number+"/"
##########################################################################









